/* Generated by Yosys 0.5 (git sha1 c3c9fbf, i686-pc-mingw32-gcc 4.8.1 -Os) */

module piposr(Din, SI, LDin, LDout, CK, Dout, SO);
  wire [3:0] _00_;
  wire [3:0] _01_;
  input CK;
  input [3:0] Din;
  output [3:0] Dout;
  input LDin;
  input LDout;
  wire [3:0] Q;
  input SI;
  output SO;
  MUX21 _02_ (
    .D0(Dout[2]),
    .D1(Q[2]),
    .S(LDout),
    .Z(_00_[2])
  );
  MUX21 _03_ (
    .D0(Dout[1]),
    .D1(Q[1]),
    .S(LDout),
    .Z(_00_[1])
  );
  MUX21 _04_ (
    .D0(Dout[0]),
    .D1(Q[0]),
    .S(LDout),
    .Z(_00_[0])
  );
  MUX21 _05_ (
    .D0(Q[2]),
    .D1(Din[1]),
    .S(LDin),
    .Z(_01_[1])
  );
  MUX21 _06_ (
    .D0(Q[1]),
    .D1(Din[0]),
    .S(LDin),
    .Z(_01_[0])
  );
  MUX21 _07_ (
    .D0(Dout[3]),
    .D1(Q[3]),
    .S(LDout),
    .Z(_00_[3])
  );
  MUX21 _08_ (
    .D0(Q[3]),
    .D1(Din[2]),
    .S(LDin),
    .Z(_01_[2])
  );
  MUX21 _09_ (
    .D0(SI),
    .D1(Din[3]),
    .S(LDin),
    .Z(_01_[3])
  );
  FFD _10_ (
    .CK(CK),
    .D(_01_[0]),
    .Q(Q[0])
  );
  FFD _11_ (
    .CK(CK),
    .D(_01_[1]),
    .Q(Q[1])
  );
  FFD _12_ (
    .CK(CK),
    .D(_01_[2]),
    .Q(Q[2])
  );
  FFD _13_ (
    .CK(CK),
    .D(_01_[3]),
    .Q(Q[3])
  );
  FFD _14_ (
    .CK(CK),
    .D(_00_[0]),
    .Q(Dout[0])
  );
  FFD _15_ (
    .CK(CK),
    .D(_00_[1]),
    .Q(Dout[1])
  );
  FFD _16_ (
    .CK(CK),
    .D(_00_[2]),
    .Q(Dout[2])
  );
  FFD _17_ (
    .CK(CK),
    .D(_00_[3]),
    .Q(Dout[3])
  );
  assign SO = Q[0];
endmodule
