/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tannerkleintop
 */
import java.text.DecimalFormat;
public class TemperatureConverterGUI extends javax.swing.JFrame {

     private javax.swing.ButtonGroup conversionGroup; // Button group for conversion type
    /**
     * Creates a new instance of TemperatureConverterGUI.
     * Initializes the form and sets up the conversion button group.
     */
    public TemperatureConverterGUI() {
        initComponents();
        conversionGroup = new javax.swing.ButtonGroup();
        conversionGroup.add(fahrenheitToCelsius);
        conversionGroup.add(celsiusToFahrenheit);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        title = new javax.swing.JLabel();
        subtitle = new javax.swing.JLabel();
        fahrenheitToCelsius = new javax.swing.JRadioButton();
        celsiusToFahrenheit = new javax.swing.JRadioButton();
        inputline = new javax.swing.JLabel();
        convertbutton = new javax.swing.JButton();
        inputbox = new javax.swing.JTextField();
        outputline = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TemperatureConverterGUI");
        setName("Title"); // NOI18N

        title.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 0, 0));
        title.setText("Temperature Converter");
        title.setName("title"); // NOI18N

        subtitle.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        subtitle.setText("Choose Conversion Type:");
        subtitle.setName("subtitle"); // NOI18N

        fahrenheitToCelsius.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        fahrenheitToCelsius.setText("Fahrenheit To Celsius");
        fahrenheitToCelsius.setName("fahrenheitToCelsius"); // NOI18N

        celsiusToFahrenheit.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        celsiusToFahrenheit.setText("Celsius To Fahrenheit");
        celsiusToFahrenheit.setName("celsiusToFahrenheit"); // NOI18N

        inputline.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        inputline.setText("Enter the temperature to convert: ");
        inputline.setName("inputline"); // NOI18N

        convertbutton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        convertbutton.setText("Convert Temperature");
        convertbutton.setName("convertbutton"); // NOI18N
        convertbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertbuttonActionPerformed(evt);
            }
        });

        inputbox.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        inputbox.setName("inputbox"); // NOI18N
        inputbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputboxActionPerformed(evt);
            }
        });

        outputline.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        outputline.setText("The temperature converts to: ");
        outputline.setName("outputline"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(convertbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(inputline)
                                    .addComponent(subtitle))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputbox, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(celsiusToFahrenheit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fahrenheitToCelsius, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(outputline))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fahrenheitToCelsius)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(celsiusToFahrenheit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputline)
                    .addComponent(inputbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(outputline)
                .addGap(18, 18, 18)
                .addComponent(convertbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void convertbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertbuttonActionPerformed
// TODO add your handling code here:

// Get the input temperature from the text field
String inputText = inputbox.getText();
double inputTemperature = Double.parseDouble(inputText); // Convert the input text to a double value

// Check if Fahrenheit to Celsius conversion is selected
if (fahrenheitToCelsius.isSelected()) {
    // Convert Fahrenheit to Celsius
    double convertedTemperature = (inputTemperature - 32) * 5 / 9;

    // Round the converted temperature to 2 decimal places
    DecimalFormat decimalFormat = new DecimalFormat("#.0");
    String formattedTemperature = decimalFormat.format(convertedTemperature);

    // Display the converted temperature in Celsius
    outputline.setText("The temperature converts to: " + formattedTemperature + " °C");
} 
// Check if Celsius to Fahrenheit conversion is selected
else if (celsiusToFahrenheit.isSelected()) {
    // Convert Celsius to Fahrenheit
    double convertedTemperature = (inputTemperature * 9 / 5) + 32;

    // Round the converted temperature to 2 decimal places
    DecimalFormat decimalFormat = new DecimalFormat("#.0");
    String formattedTemperature = decimalFormat.format(convertedTemperature);

    // Display the converted temperature in Fahrenheit
    outputline.setText("The temperature converts to: " + formattedTemperature + " °F");
} 
// No conversion type selected
else {
    // Display an error message asking the user to select a conversion type
    outputline.setText("Please select a conversion type.");
}

    }//GEN-LAST:event_convertbuttonActionPerformed

    private void inputboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputboxActionPerformed
        // TODO add your handling code here:
         convertbuttonActionPerformed(evt);
    }//GEN-LAST:event_inputboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TemperatureConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TemperatureConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TemperatureConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TemperatureConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TemperatureConverterGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton celsiusToFahrenheit;
    private javax.swing.JButton convertbutton;
    private javax.swing.JRadioButton fahrenheitToCelsius;
    private javax.swing.JTextField inputbox;
    private javax.swing.JLabel inputline;
    private javax.swing.JLabel outputline;
    private javax.swing.JLabel subtitle;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
