/* Generated by Yosys 0.5 (git sha1 c3c9fbf, i686-pc-mingw32-gcc 4.8.1 -Os) */

module counter(CLK, LD_L, CLR_L, LD_DATA, ENP, ENT, Q, RCO);
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  input CLK;
  input CLR_L;
  input ENP;
  input ENT;
  input [3:0] LD_DATA;
  input LD_L;
  output [3:0] Q;
  output RCO;
  AND2 _16_ (
    .A(ENT),
    .B(ENP),
    .Z(_01_)
  );
  AND3 _17_ (
    .A(_01_),
    .B(Q[0]),
    .C(Q[1]),
    .Z(_02_)
  );
  XNOR _18_ (
    .A(_02_),
    .B(Q[2]),
    .Z(_03_)
  );
  OAI21 _19_ (
    .A1(LD_L),
    .A2(LD_DATA[2]),
    .B(CLR_L),
    .Z(_04_)
  );
  AOI21 _20_ (
    .A1(_03_),
    .A2(LD_L),
    .B(_04_),
    .Z(_00_[2])
  );
  AND2 _21_ (
    .A(_01_),
    .B(Q[0]),
    .Z(_05_)
  );
  XNOR _22_ (
    .A(_05_),
    .B(Q[1]),
    .Z(_06_)
  );
  OAI21 _23_ (
    .A1(LD_DATA[1]),
    .A2(LD_L),
    .B(CLR_L),
    .Z(_07_)
  );
  AOI21 _24_ (
    .A1(_06_),
    .A2(LD_L),
    .B(_07_),
    .Z(_00_[1])
  );
  XNOR _25_ (
    .A(_01_),
    .B(Q[0]),
    .Z(_08_)
  );
  OAI21 _26_ (
    .A1(LD_DATA[0]),
    .A2(LD_L),
    .B(CLR_L),
    .Z(_09_)
  );
  AOI21 _27_ (
    .A1(_08_),
    .A2(LD_L),
    .B(_09_),
    .Z(_00_[0])
  );
  INV _28_ (
    .A(Q[3]),
    .Z(_10_)
  );
  AND3 _29_ (
    .A(Q[0]),
    .B(Q[1]),
    .C(Q[2]),
    .Z(_11_)
  );
  XNOR _30_ (
    .A(_11_),
    .B(Q[3]),
    .Z(_12_)
  );
  MUX21 _31_ (
    .D0(_10_),
    .D1(_12_),
    .S(_01_),
    .Z(_13_)
  );
  OAI21 _32_ (
    .A1(LD_DATA[3]),
    .A2(LD_L),
    .B(CLR_L),
    .Z(_14_)
  );
  AOI21 _33_ (
    .A1(_13_),
    .A2(LD_L),
    .B(_14_),
    .Z(_00_[3])
  );
  AND4 _34_ (
    .A(Q[1]),
    .B(Q[3]),
    .C(Q[2]),
    .D(Q[0]),
    .Z(_15_)
  );
  AND2 _35_ (
    .A(_15_),
    .B(ENT),
    .Z(RCO)
  );
  FFD _36_ (
    .CK(CLK),
    .D(_00_[0]),
    .Q(Q[0])
  );
  FFD _37_ (
    .CK(CLK),
    .D(_00_[1]),
    .Q(Q[1])
  );
  FFD _38_ (
    .CK(CLK),
    .D(_00_[2]),
    .Q(Q[2])
  );
  FFD _39_ (
    .CK(CLK),
    .D(_00_[3]),
    .Q(Q[3])
  );
endmodule
